# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: "3.4"

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  opencommerce-admin:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - "4082:4082"
    volumes:
      - .:/app
      - opencommerce_admin_node_modules:/app/node_modules
volumes:
  opencommerce_admin_node_modules:
